version: "3"
services:
  app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDB
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - app-db
